# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 532977b85cb73d678aa0354cdb3a1c9e6a031fb8c28ba0ee074bad8a6173eb0dce2627d930251c236d11cd18f7414a972d65e75d7facc94115a235a67d33e931

test:
  secret_key_base: dbe4f9c01485ab9395332080e13eb1d0f9d76f5f9164e8b9d0345354bd3acbd62548af708d8356cab42b4a77ef2a9301af9d400316a6e14c285a74cda9233ffc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
